### ISSUE TITLE
Tags not displayed in asset properties after import with CSV Asset Importer ...

### ISSUE THREAD

**Issue by KonradMoser** [Adobe-Consulting-Services/acs-aem-tools#167]
Environment: AEM 6.2 + Dynamic Media.
Steps to reproduce:
You will need some sample files which you will find on https://adobe.ly/2hFAFdj

1. Install CSV Asset Importer
2. Create a Tag-Namespace (called test_namespace)
3. Create a Tag (called test_tag)
4. Download the CSV file ("import02.csv")
5. Download the Assets ("Sample Pictures.zip")
6. Extract the ZIP-File with the pictures to a folder of your choice ( will be needed again when you choose the "Absolute File Dump Location".
6. Start CSV Asset Importer
7. Select import02.csv as the CSV-File.
8. Set the "Absolute File Dump Location"
9. Import the assets.

As a result you should have a DEMO-Folder in AEM Assets. The imported pictures are available in this folder. However no tag(s) are associated with this pictures, even though the import imported the tagging information. When I had a look to /content/dam/demo/Pic01.jpg/jcr:content/metadata I could clearly see that the metadata has been imported an it resides in cq:tag, but they are not displayed in the asset properties.

I also created a package (asset_imperter_tag_issue.zip) which reflects the result of the asset import on my machine (availablable on https://adobe.ly/2hFAFdj). 

Hints to overcome this issue are welcome.
Thanks: Konrad

**Comment by davidjgonzalez** [comment]
Csv asset importer doesn't create tags. Check
Out acs tools TagMaker if you want to create tags themselves.

You should extract all your tags to a diff CSV and import them as their own content models via TagMaker. If you have exes chops I don't expect deriving the tags CSV should be too dlong faculty using th cq:tags property column in your asset import sheet. 

HTH

**Comment by justinedelson** [comment]
@KonradMoser The problem is that the CSV references the wrong Tag ID. With the package you provided, the Tag ID would be `test_namespace:test_tag`. You have `Test_Namespace:Test_Tag`. I suppose we could do some kind of validation that the tags referenced in the CSV file actually exist and warn if they don't. @davidjgonzalez WDYT?

**Comment by davidjgonzalez** [comment]
What sort of warning? in the logs? as the result of the execution on the web page?

TBH I don't love putting in a single corner case for when cq:tags are provided (optional), and this is the first time this issue has been reported.

@KonradMoser do you think having a message stating "Test_Namespace:Test_Tag could not be resolved to a tag" wouldve helped? I sounds like you saw the values you specified in the CSV were in the correct property on the asset... at that point, i would've assumed the problem is w/ the tags or with the widget displaying the tags, since the Asset has the exact values that were specified in the CSV file? 


Also, iirc there is an event listener that will remove tags that dont exist, but that might only effect pages (since it doesnt seem to have stripped @KonradMoser's malformed cq:tags values out). If that effects Assets, i think its more an impetus to log a message since then it would appear that the csv asset importer didnt work (as the specified values are removed from the property).
