### ISSUE TITLE
Unable to update sling resource type via resource type updater

### ISSUE THREAD

**Issue by Vl975532** [Adobe-Consulting-Services/acs-aem-tools#192]
Hi - I tried the above steps and when i click on update sling resource type, i am getting the process is executing for a long time and nothing is happening after this. Please help

**Comment by davidjgonzalez** [comment]
@vl975532 are there any errors in your logs? Would you provided the CSV file you're using as well (assuming it doesn't contain any secret info)

**Comment by Vl975532** [comment]
[Update.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-tools/files/1050685/Update.xlsx)

PFA. i do not see anything in error logs

**Comment by davidjgonzalez** [comment]
And lastly, what version of aem and acs tools are you using?

**Comment by Vl975532** [comment]
i am using AEM 6.0 and acs tools 4.0

**Comment by davidjgonzalez** [comment]
An to be clear, you are uploading a CSV version of the Excel file right?

[Update.csv.rename-me.txt](https://github.com/Adobe-Consulting-Services/acs-aem-tools/files/1052247/Update.csv.rename-me.txt)

**Comment by davidjgonzalez** [comment]
@Vl975532 ah - so if you check your bundles (/system/console/bundles) youll see the ACS AEM Tools bundle is not started due to unsatisfied dependencies.

It looks like 6.0 support fell off in v0.0.40 an the last version to support AEM 6.0 is v0.0.30 - so try using that:

https://github.com/Adobe-Consulting-Services/acs-aem-tools/releases/tag/acs-aem-tools-0.0.30

This should be documented more clearly.
