### ISSUE TITLE
vlt rcp url to be changed

### ISSUE THREAD

**Issue by tyge68** [Adobe-Consulting-Services/acs-aem-tools#91]
In recent addition of the VLT RCP tool, it uses the old url of rcp, the new one is /system/jackrabbit/filevault/rcp in latest VLT RCP bundle 3.1.18 release.

**Comment by davidjgonzalez** [comment]
Thanks! 

We should make sure to capture this in the documentation; I can see ppl using older versions becoming a confused as to why it's not working.

**Comment by justinedelson** [comment]
Is there value in making this configurable? Or would we always recommend that everyone use the latest version?

**Comment by tyge68** [comment]
I think it make sense to use latest version of vlt rcp bundle 3.1.18. In
the worse case we can document how to change the url in the apps.js script.

**Comment by tyge68** [comment]
Yes it would be nice to create a page for the documentation of this new
tool. As this is the first time I added a tool here I may need some
pointers where to start.
cheers
-Thierry

**Comment by davidjgonzalez** [comment]
@tyge68 Check out the readme for ... https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io

You can fork the repo, and create a new "feature post" w the documentation. [1]  -- Since im lazy, i typically copy an existing feature post that is similar to what i want to make, and update. Let me know if you need any help, etc. Im happy to make a thumbnail for the front page if you dont like fiddling around w gfx.

[1] https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/tree/master/_posts/acs-aem-tools/features
